In [68]:
import pandas as pd

In [69]:
df = pd.read_csv("../../datasets/originals/CPU_benchmark_v4.csv")

In [70]:
df.isna().sum()

cpuName           0
price          1858
cpuMark           0
cpuValue       1858
threadMark        0
threadValue    1858
TDP             685
powerPerf       685
cores             0
testDate          0
socket            0
category          0
dtype: int64

In [71]:
df.head()

,cpuName,price,cpuMark,cpuValue,threadMark,threadValue,TDP,powerPerf,cores,testDate,socket,category
0,AMD Ryzen Threadripper PRO 5995WX,NaN,108822,NaN,3330,NaN,280.0,388.65,64,2022,sWRX8,Desktop
1,AMD EPYC 7763,7299.99,88338,12.10,2635,0.36,280.0,315.49,64,2021,SP3,Server
2,AMD EPYC 7J13,NaN,86006,NaN,2387,NaN,NaN,NaN,64,2021,unknown,Server
3,AMD EPYC 7713,7060.00,85861,12.16,2727,0.39,225.0,381.6,64,2021,SP3,Server
4,AMD Ryzen Threadripper PRO 3995WX,6807.98,83971,12.33,2626,0.39,280.0,299.9,64,2020,sWRX8,Desktop

In [72]:
df['socket'].unique()

<StringArray>
[           'sWRX8',              'SP3',          'unknown',
            'sTRX4',        'FCLGA4189',          'LGA4189',
              'AM4',         'LGA 1700',        'FCLGA1700',
        'FCLGA3647',
 ...
   'H-PBGA479, PPG', 'PPGA478, H-PBGA4',       'Socket 370',
           'BGA441',   'Socket A (462)',           'BGA518',
  'BGA2, microPGA2',          'PBGA479',           'PGA423',
         'NanoBGA2']
Length: 203, dtype: str

In [74]:
df = df[df['category'] == 'Desktop'] 
df = df[df['socket'].isin(['AM4', 'AM2+,AM3', 'AM3', 'AM3+', 'LGA 1155', 'LGA 1700'])] # TODO: better compatibility subset
df = df[~df['cpuName'].str.contains('Apple')]
df.head()

,cpuName,price,cpuMark,cpuValue,threadMark,threadValue,TDP,powerPerf,cores,testDate,socket,category
39,AMD Ryzen 9 5950X,649.74,46195,71.10,3498,5.38,105.0,439.96,16,2020,AM4,Desktop
44,Intel Core i9-12900KS,779.98,44243,56.72,4317,5.53,150.0,294.95,8,2022,LGA 1700,Desktop
63,AMD Ryzen 9 5900X,393.03,39457,100.39,3494,8.89,105.0,375.78,12,2020,AM4,Desktop
64,AMD Ryzen 9 3950X,650.00,39157,60.24,2738,4.21,105.0,372.92,16,2019,AM4,Desktop
79,AMD Ryzen 9 5900,NaN,34721,NaN,3432,NaN,65.0,534.17,12,2021,AM4,Desktop

In [75]:
df

,cpuName,price,cpuMark,cpuValue,threadMark,threadValue,TDP,powerPerf,cores,testDate,socket,category
39,AMD Ryzen 9 5950X,649.74,46195,71.10,3498,5.38,105.0,439.96,16,2020,AM4,Desktop
44,Intel Core i9-12900KS,779.98,44243,56.72,4317,5.53,150.0,294.95,8,2022,LGA 1700,Desktop
63,AMD Ryzen 9 5900X,393.03,39457,100.39,3494,8.89,105.0,375.78,12,2020,AM4,Desktop
64,AMD Ryzen 9 3950X,650.00,39157,60.24,2738,4.21,105.0,372.92,16,2019,AM4,Desktop
79,AMD Ryzen 9 5900,NaN,34721,NaN,3432,NaN,65.0,534.17,12,2021,AM4,Desktop
...,...,...,...,...,...,...,...,...,...,...,...,...
3209,AMD Athlon II X2 250u,24.95,604,24.22,632,25.32,25.0,24.17,2,2010,AM3,Desktop
3312,AMD Sempron 145,35.99,505,14.04,989,27.47,45.0,11.23,1,2010,AM3,Desktop
3318,AMD Sempron 150,14.95,498,33.32,1079,72.16,45.0,11.07,1,2011,AM3,Desktop
3350,AMD Sempron 140,11.95,471,39.42,1044,87.38,45.0,10.47,1,2009,AM3,Desktop
3469,AMD Athlon II 170u,24.00,357,14.86,728,30.34,20.0,17.83,1,2010,"AM2+,AM3",Desktop